### ISSUE TITLE
Why isn't this on the chrome store!?

### ISSUE THREAD

**Issue by Shikkic** [charleslai/restumble#1]
It's really easy to get extensions approved, this could be really popular! Get a nice logo, get it on chrome store, blast through all channels. :sun_with_face:

**Comment by Shikkic** [comment]
for example: https://chrome.google.com/webstore/detail/mouthsounds/mffikfabjgdafkejajgkbheipanihnfh

**Comment by sup** [comment]
loool it is on the chromestore :o https://chrome.google.com/webstore/detail/restumble/ailekjbcdiedcfdjjnhlgdnlbdlphnhd?hl=en didnt do any screenshots tho

**Comment by Shikkic** [comment]
Needs screenshots

**Comment by Shikkic** [comment]
Also repo could use a screenshot too
